// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSchedules() {
  return window['go']['main']['App']['GetSchedules']();
}

export function GetString() {
  return window['go']['main']['App']['GetString']();
}
