// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {schedule} from '../models';

export function GetSchedules():Promise<Array<schedule.Schedule>>;

export function GetString():Promise<string>;
