// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddSchedule(arg1:model.Schedule):Promise<void>;

export function DeleteSchedule(arg1:string):Promise<void>;

export function GetSchedules():Promise<Array<model.Schedule>>;

export function ModifySchedule(arg1:model.Schedule):Promise<void>;
